[package]
name = "orion-chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ecdsa = {version = "0.16.8"}
hex = "0.4.3"
k256 = "0.13.1"
rand = {version = "0.8.5"}
